# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: Test-pak

jobs:
  Test-pak:
    runs-on: ubuntu-24.04
    container:
      image: runiverse/base:latest
    steps:
#      - uses: r-lib/actions/setup-r@v2
      - name: Clone a package
        shell: bash
        run: |
          git clone https://github.com/cran/ggplot2
      - name: Test devel pak
        run: |
          setwd('ggplot2')
          install.packages('pak', repos = 'https://r-lib.github.io/p/pak/devel/source/linux-gnu/x86_64')
          pak::pkg_sysreqs('.', upgrade = FALSE)
        shell: Rscript {0}
