# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: Test-pak

jobs:
  Test-pak:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/r-universe-org/build-source:latest
    steps:
      - name: test
        shell: bash
        run: |
          git clone https://github.com/cran/ggplot2
          cd ggplot2
          R -e "pak::pkg_sysreqs('.', upgrade = FALSE)"

