# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:
  workflow_dispatch:

name: r-universe

jobs:
  r-universe-linux:
    runs-on: ubuntu-24.04${{ matrix.arch == 'arm' && '-arm' || '' }}
    container:
      image: runiverse/base:latest
    strategy:
      fail-fast: false
      matrix:
        pak: [ 'stable', 'devel' ]
        arch: [ 'intel', 'arm' ]
    steps:
      - name: Install from R-universe
        run: |
          install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/${{matrix.pak}}/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))
          pak::pak('enrichplot')
        shell: Rscript {0}

  r-universe-macos:
    runs-on: macos-${{ matrix.arch == 'arm' && '15' || '13' }}
    strategy:
      fail-fast: false
      matrix:
        pak: [ 'stable', 'devel' ]
        arch: [ 'intel', 'arm' ]
    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: Install from R-universe
        run: |
          options(repos = c(CRAN = 'https://cran.r-project.org', BIOC = 'https://bioc.r-universe.dev'))
          install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/${{matrix.pak}}/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))
          pak::pak('enrichplot')
        shell: Rscript {0}

  r-universe-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        pak: [ 'stable', 'devel' ]
    steps:
      - name: Install from R-universe
        run: |
          options(repos = c(CRAN = 'https://cran.r-project.org', BIOC = 'https://bioc.r-universe.dev'))
          install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/${{matrix.pak}}/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))
          pak::pak('enrichplot')
        shell: Rscript {0}
