# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:
  workflow_dispatch:

name: test-sysreqs

jobs:
  test-sysreqs:
    runs-on: ubuntu-24.04${{ matrix.arch == 'arm' && '-arm' || '' }}
    container:
      image: runiverse/base:latest
    strategy:
      fail-fast: false
      matrix:
        pak: [ 'stable', 'devel' ]
        arch: [ 'intel', 'arm' ]
    steps:
#      - uses: r-lib/actions/setup-r@v2
      - name: Clone a package
        shell: bash
        run: |
          git clone https://github.com/cran/tidyverse $GITHUB_WORKSPACE

      - name: Test pak
        run: |
          install.packages('pak', repos = paste0('https://r-lib.github.io/p/pak/${{matrix.pak}}/source/linux-gnu/', R.Version()$arch))
          pak::pkg_sysreqs('.', upgrade = FALSE)
        shell: Rscript {0}
